force-app/main/default/objects/Club__c/Club__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club__c/fields/Club_Manager__c.field-meta.xml
<CustomField>
    <fullName>Club_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Club Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clubs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Club__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <label>Stadium</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{0000}</displayFormat>
        <label>Match #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Match_Date__c.field-meta.xml
<CustomField>
    <fullName>Match_Date__c</fullName>
    <label>Match Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_1__c.field-meta.xml
<CustomField>
    <fullName>Team_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team 1</label>
    <referenceTo>Club__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Team1_Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_1_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_1_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team 1 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_2__c.field-meta.xml
<CustomField>
    <fullName>Team_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team 2</label>
    <referenceTo>Club__c</referenceTo>
    <relationshipLabel>Matches (Team 2)</relationshipLabel>
    <relationshipName>Team2_Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_2_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_2_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Team 2 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match_Goal__c/Match_Goal__c.object-meta.xml
<CustomObject>
    <label>Match Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Goal__c/fields/Goal_Type__c.field-meta.xml
<CustomField>
    <fullName>Goal_Type__c</fullName>
    <label>Goal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal Goal</fullName>
                <default>true</default>
                <label>Normal Goal</label>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Free Kick</fullName>
            </value>
            <value>
                <fullName>Own Goal</fullName>
            </value>
            <value>
                <fullName>Corner Kick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match_Goal__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Match Goals</relationshipLabel>
    <relationshipName>Match_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match_Goal__c/fields/Minute__c.field-meta.xml
<CustomField>
    <fullName>Minute__c</fullName>
    <label>Minute</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match_Goal__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Match Goals</relationshipLabel>
    <relationshipName>Match_Goals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match_Goal__c/fields/Scoring_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Team__c</fullName>
    <label>Scoring Team</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Club__c.field-meta.xml
<CustomField>
    <fullName>Club__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Club</label>
    <referenceTo>Club__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Goals_Scored__c.field-meta.xml
<CustomField>
    <fullName>Goals_Scored__c</fullName>
    <label>Goals Scored</label>
    <summaryForeignKey>Match_Goal__c.Player__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <label>Photo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Goalkeeper</fullName>
            </value>
            <value>
                <fullName>Defender</fullName>
            </value>
            <value>
                <fullName>Midfielder</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FootballManager.cls
public class FootballManager {
    
    @AuraEnabled(cacheable=True)
    public static List<Player__c> getPlayers() {
        List<Player__c> playerList = [SELECT Id, Name, Position__c, Nationality__c, Club__r.Name, Goals_Scored__c FROM Player__c];
        return playerList;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Player__c getPlayerDetailsById(Id playerId) {
        Player__c player = [SELECT Id, Name, Position__c, Club__r.Name, Goals_Scored__c, Nationality__c, Photo__c 
                            FROM Player__c 
                            WHERE Id = :playerId];
        return player;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Club__c> getClubs() {
        List<Club__c> clubList = [SELECT Id, Name, Logo__c FROM Club__c];
        return clubList;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Club__c getClubDetailsById(Id clubId) {
        Club__c club = [SELECT Id, Name, Logo__c, Club_Manager__r.Name, Stadium__c FROM Club__c WHERE Id = :clubId];
        return club;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Player__c> getPlayersByClub(Id clubId) {
        List<Player__c> players = [SELECT Id, Name, Position__c, Photo__c, Nationality__c, Goals_Scored__c FROM Player__c
                             WHERE Club__c = :clubId ORDER BY Position__c, Name];
        return players;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Match__c> getMatches() {
        List<Match__c> matchList = [SELECT Id, Match_Date__c, Team_1__r.Name, Team_2__r.Name, Team_1_Score__c, Team_2_Score__c FROM Match__c];
        return matchList;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static Match__c getMatchDetailsById(Id matchId) {
        Match__c match = [
            SELECT Id, Match_Date__c, Team_1__r.Name, Team_1__r.Logo__c, Team_2__r.Logo__c, Team_2__r.Name, Team_1_Score__c, Team_2_Score__c,
                   (SELECT Id, Player__r.Name, Scoring_Team__c, Goal_Type__c, Minute__c FROM Match_Goals__r)
            FROM Match__c
            WHERE Id = :matchId
        ];
        return match;
    }

}